server:
  port: 8080
  tomcat:
    threads:
      max: 15

spring:
  application.name: servlet-app
  security:
    user:
      name: user
      password: user
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        onLikeEvent-in-0:
          destination: likes
          group: web

app:
  remote-service-url: http://localhost:9999

logging:
  org.springframework.amqp.rabbit: DEBUG
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG